EXPORTVIDEO = False

PRETTY = True
CINEMATICSEQUENCES = False
HOLLOWOUTFATISLANDS = True

FORCE_SHOWDEBUG = False
FORCE_SHOWCENTERS = False
FORCE_SHOWCOLLISIONS = False

FORCE_HIDEEXPENSIVERENDERING = True

OVERSIZESPRITESCALE = 2.0
