UV_NAME = "Master_UVMap"
UV_MARGIN = 0.0025
UV_MINIMIZESTRETCH_ITERATIONS = 100
UV_MINIMIZESTRETCH_SUBITERATIONS = 10
#Total minimize stretch iterations is the product of UV_MINIMIZESTRETCH_ITERATIONS * UV_MINIMIZESTRETCH_SUBITERATIONS.